[tool.poetry]
name = "ipwndfu"
version = "2.0.0"
description = "The DFU exploitation toolkit for Apple devices"
authors = ["axi0mX <axi0mXor@gmail.com>"]

[tool.poetry.scripts]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
pylint = "^2.12.2"
pytest = "^7.0.1"
mypy = "^0.931"
pre-commit = "^2.17.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
