name: Desired flake8 / pylint

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      python_version: 3.10
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ env.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip poetry
          poetry install
      - name: Linting the code with flake8
        run: |
          poetry run flake8 src/
      - name: Type flow analysis with MyPy
        run: |
          poetry run mypy .
